### ISSUE TITLE
System.NullReferenceException when using a custom IAmAHandlerFactoryAsync with a custom validation pipeline

### ISSUE THREAD

**Issue by rvanmaanen** [BrighterCommand/Brighter#268]
Hi,

I'm having an issue when trying to build a custom validation pipeline together with a custom handlerfactory to support StructureMap.

The following code is used to build the command processor:

```
var commandProcessor = CommandProcessorBuilder.With()
.Handlers(new HandlerConfiguration(subscriberRegistry, new StructureMapHandlerFactory(container)))
.Policies(policyRegistry)
.NoTaskQueues()
.RequestContextFactory(new InMemoryRequestContextFactory())
.Build();
```

The StructureMapHandlerFactory gets passed an instance of IContainer (structuremap's interface).
The container knows all the IHandleRequestsAsync and IHandleRequestsAsync<> implementations through the following 2 statements, which scans the assemblies and registers the implementions by the name of their type:

```
scanner.AddAllTypesOf<IHandleRequestsAsync>().NameBy(type => type.Name);
scanner.AddAllTypesOf(typeof(IHandleRequestsAsync<>)).NameBy(type => type.Name);
```

Then the StructureMapHandlerFactory is quite straightforward, although I feel something goes wrong at this point (something with the difference between IHandleRequestsAsync and IIHandleRequestsAsync&lt;TRequest&gt; maybe?

```
public IHandleRequestsAsync Create(Type handlerType)        {
             //This doesn't work for the ValidationHandler, probably because of the generic typing
             //return _container.GetInstance<IHandleRequestsAsync>(handlerType.Name);

            var allRequestHandlers = _container.Model.AllInstances.Where(instance => instance.PluginType == typeof(IHandleRequestsAsync) || instance.PluginType == typeof(IHandleRequestsAsync<>));
            var instanceForType = allRequestHandlers.Single(instance => instance.Name == handlerType.Name);

            return instanceForType.Get<IHandleRequestsAsync>();
}
```

This all works fine for the reguler RequestHandlerAsync implementations, but now we have the following handler (together with a custom RequestHandlerAttribute and an interface ICommandValidator which is implemented by the TRequest object passed in) . The code is based on the sample application for Tasks (https://github.com/BrighterCommand/Contrib/tree/master/samples/TaskList/src/Tasks/Ports/Commands & https://github.com/BrighterCommand/Contrib/tree/master/samples/TaskList/src/Tasks/Ports/Handlers):

```
public class ValidationHandler<TRequest> : RequestHandlerAsync<TRequest>
        where TRequest : class, IRequest, ICommandValidator
    {
        public override async Task<TRequest> HandleAsync(TRequest command, CancellationToken cancellationToken = default(CancellationToken))
        {
            if (!command.IsValid())
            {
                throw new ArgumentException("The commmand was not valid");
            }

            return await base.HandleAsync(command, cancellationToken);
        }
}
```

The requesthandlerattribute has the following implementation for GetHandlerType:

`return typeof(ValidationHandler<>);`

When deploying this code and firing off a command I get the following stacktrace:

```
   at Paramore.Brighter.AsyncHandlerFactory`1.CreateAsyncRequestHandler()
   at Paramore.Brighter.PipelineBuilder`1.<>c__DisplayClass15_0.<PushOntoAsyncPipeline>b__0(RequestHandlerAttribute attribute)
   at Paramore.Brighter.Extensions.EnumerationExtensions.Each[T](IEnumerable`1 collection, Action`1 doThis)
   at Paramore.Brighter.PipelineBuilder`1.PushOntoAsyncPipeline(IEnumerable`1 attributes, IHandleRequestsAsync`1 lastInPipeline, IRequestContext requestContext, Boolean continueOnCapturedContext)
   at Paramore.Brighter.PipelineBuilder`1.BuildAsyncPipeline(RequestHandlerAsync`1 implicitHandler, IRequestContext requestContext, Boolean continueOnCapturedContext)
   at Paramore.Brighter.PipelineBuilder`1.<>c__DisplayClass12_0.<BuildAsync>b__0(RequestHandlerAsync`1 handler)
   at Paramore.Brighter.Extensions.EnumerationExtensions.Each[T](IEnumerable`1 collection, Action`1 doThis)
   at Paramore.Brighter.PipelineBuilder`1.BuildAsync(IRequestContext requestContext, Boolean continueOnCapturedContext)
   at Paramore.Brighter.CommandProcessor.<SendAsync>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at "controller calling ICommandProcessor.SendAsync(...)"
```
 
Could you please have a look and help me to see what I'm doing wrong or what is causing this exception?

Thanks!

**Comment by rvanmaanen** [comment]
Noticed you changed some code around there in the master branch, so just downloaded the Paramore.Brighter.7.1.68 artifact and tried that. Still no success, still giving a nullreference at line 46 (as far as i can tell by debugging) in this class https://github.com/BrighterCommand/Brighter/blob/master/src/Paramore.Brighter/AsyncHandlerFactory.cs:

`IHandleRequestsAsync<TRequest> handleRequestsAsync = (IHandleRequestsAsync<TRequest>) factory.Create(handlerType);`

Can't figure out why, the factory which is used there is my custom factory which does return an instance of the ValidationHandler class, which (by extending from RequestHandlerAsync<TRequest>) does implement the IHandleRequestAsync interfaces and should be castable to these interfaces.

**Comment by rvanmaanen** [comment]
Got some sleep, downloaded the sources and had another look. Figured out the problem wasn't in the AsyncHandlerFactory, but my custom ActionHandlerFactory not properly returning a value in all cases.

Rewrote the implementation to the following, which works:

```
public IHandleRequestsAsync Create(Type handlerType)
        {
            IHandleRequestsAsync instance;

            if (handlerType.IsGenericType)
            {
                instance = _container.ForGenericType(handlerType.GetGenericTypeDefinition())
                    .WithParameters(handlerType.GetGenericArguments().First())
                    .GetInstanceAs<IHandleRequestsAsync>();
            }
            else
            {
                instance = _container.GetInstance<IHandleRequestsAsync>(handlerType.GetNameForBrighter());
            }

            return instance;
        }
```
It still depends on naming the instances registered in the StructureMap container, else StructureMap can't distinguish between the different instances of IHandleRequestsAsync.
