### ISSUE TITLE
DynamoDB Outbox Hot Partition

### ISSUE THREAD

**Issue by jtsalva** [BrighterCommand/Brighter#2810]
### Describe the bug
`Paramore.Brighter.Outbox.DynamoDB` throttling on `DynamoDbOutbox.OutstandingMessages`. This is despite the table and GSIs being 'on-demand/pay per request'. According to AWS docs 'A hot partition can cause throttling if the partition limits of **3000 RCU and 1000 WCU per second are exceeded**.'

The schema for the Outstanding index is:
```
hash_key_name: Topic
hash_key_type: STRING
range_key_name: CreatedTime
range_key_type: NUMBER
```

We encounter a hot partition where we're publishing only to a single topic at a rate exceeding the limit imposed by AWS Dynamo itself.

### Exceptions
```
System.AggregateException: One or more errors occurred. (Throughput exceeds the current capacity for one or more global secondary indexes. DynamoDB is automatically scaling your index so please try again shortly.)
 ---> Amazon.DynamoDBv2.AmazonDynamoDBException: Throughput exceeds the current capacity for one or more global secondary indexes. DynamoDB is automatically scaling your index so please try again shortly.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at OpenTelemetry.Contrib.Instrumentation.AWS.Implementation.AWSTracingPipelineHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.DynamoDBv2.DocumentModel.Search.GetNextSetHelperAsync(CancellationToken cancellationToken)
   at Amazon.DynamoDBv2.DataModel.AsyncSearch`1.GetNextSetAsync(CancellationToken cancellationToken)
   at Paramore.Brighter.Outbox.DynamoDB.DynamoDbOutbox.PageAllMessagesAsync(QueryOperationConfig queryConfig, CancellationToken cancellationToken) in /_/src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs:line 411
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Paramore.Brighter.Outbox.DynamoDB.DynamoDbOutbox.OutstandingMessages(Double millisecondsDispatchedSince, Int32 pageSize, Int32 pageNumber, Dictionary`2 args) in /_/src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs:line 304
   at Paramore.Brighter.ExternalBusServices.BackgroundDispatchUsingSync(Int32 amountToClear, Int32 minimumAge, Dictionary`2 args) in /_/src/Paramore.Brighter/ExternalBusServices.cs:line 315
```

### Further technical details
- Paramore.Brighter@9.6.1
- Paramore.Brighter.Outbox.DynamoDB@9.6.1

**Comment by iancooper** [comment]
Thanks @jtsalva. My best guess is that topic hash key is what is causing the issue here. I would suspect that we would need to partition the topic key in order to remove the hotspot on the table caused by everything hashing to one location: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-sharding.html

As we don't need the suffix to read, because we are just looking for outstanding messages on a given topic, I believe that the random partition strategy ought to work for us and give a relatively good distribution of requests.

**Comment by iancooper** [comment]
This explanation is perhaps clearer: https://www.dynamodbguide.com/leaderboard-write-sharding/

We may need to allow you to configure the number of partitions we use as part of the outbox configuration, as there is a trade off between distributing writes and the need to use a scatter-gather approach to find all the outstanding messages.

**Comment by iancooper** [comment]
An open question here may be if we roll this back to V9 or just support from V10. That depends a little bit on how fast we can get the V10 pre-release out

**Comment by jtsalva** [comment]
That makes sense to me. Guessing we should add a new property like `TopicShard` to contain value `{topic}_{shard}`. Then update both indexes, outstanding and dispatched, to use `TopicShard` as the PK. Or should we just focus on `OutstandingMessages` for now?

Wonder how to arrive at a good default value

**Comment by iancooper** [comment]
>Or should we just focus on OutstandingMessages for now?
My gut would be to fix the GSI and leave the table for now, to see what emerges

>Wonder how to arrive at a good default value for number of shards
I think we should make it a config value, so that you can set, but keep the default low, say 3, as we will need to gather across the partitions, so it's not without a cost in latency.

**Comment by jtsalva** [comment]
For the time being, is it possible and would it make sense to effectively 'turn off' any sort of outbox with Brighter in it's current state? We understand we'd potentially be trading off throughput but gaining our preference to not unknowingly drop messages.

**Comment by iancooper** [comment]
@jtsalva Let me move the questions to a discussion and out of this issue

**Comment by iancooper** [comment]
@jtsalva See https://github.com/BrighterCommand/Brighter/discussions/2811

**Comment by jtsalva** [comment]
Working on a draft PR, will submit for feedback when ready :)

**Comment by iancooper** [comment]
> Working on a draft PR, will submit for feedback when ready :)

Look forward to it
