### ISSUE TITLE
System.InvalidOperationException: You cannot enqueue more items than the buffer length

### ISSUE THREAD

**Issue by holytshirt** [BrighterCommand/Brighter#846]
**Describe the bug**
When callign `End()` on the dispatcher

**To Reproduce**
When as service is stopped `_dispatcher.End().Wait();` is called we are seeing these errors .

```
2019-10-30 13:07:46,055 [225] ERROR (null) Paramore.Brighter.ServiceActivator.MessagePumpBase`1[[blah.Event, blah, Version=21.0.0.0, Culture=neutral, PublicKeyToken=null]] (null) (null) - MessagePump: Exception receiving messages from blah.Event on thread # 225
System.InvalidOperationException: You cannot enqueue more items than the buffer length
   at Paramore.Brighter.Channel.Enqueue(Message[] messages)
   at Paramore.Brighter.Channel.Receive(Int32 timeoutinMilliseconds)
   at Paramore.Brighter.ServiceActivator.MessagePumpBase`1.<Run>d__25.MoveNext()
```

Seems to happen if you have a lot of consumers with performers.

**Expected behavior**
Should shut down cleanly

**Comment by holytshirt** [comment]
Fixed in release v8.1.11
